apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-deployment
  labels:
    app: my-app
    version: b
spec:
  replicas: 2   # 40% traffic (2 out of 5 total pods)
  selector:
    matchLabels:
      app: my-app
      version: b
  template:
    metadata:
      labels:
        app: my-app
        version: b
    spec:
      containers:
      - name: my-app
        image: nginx:latest   # Version B image
        ports:
        - containerPort: 80